pageturner/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()

router.register(r"books", views.BookAPIViewSet)
router.register(r"book_collections", views.BookCollectionViewSet)

urlpatterns = [
    path("v1/", include("dj_rest_auth.urls")),
    path("v1/registration/", include("dj_rest_auth.registration.urls")),
    path("", include(router.urls)),
    path("recs/", views.RecommendedBooks.as_view(), name="recommended_books"),
    path(
        "personal_recs/",
        views.PersonalRecommendations.as_view(),
        name="personal_recommendations",
    ),
    path(
        "friends_recs/", views.FriendsRecommendations.as_view(), name="friends_recommendations"
    ),
    path("lucky_book/", views.show_lucky_book, name="lucky_book"),
    path("bookmark_book/<int:pk>/", views.bookmark_book, name="bookmark_book"),
    path("search_bar/", views.SearchBarApiListView.as_view(), name="search_bar"),
    path(
        "search_filters/",
        views.SearchFiltersApiListView.as_view(),
        name="search_filters",
    ),
    # # email subscription
    # path('email_subscription/', email_subscription, name="email_subscription")
]

urlpatterns += [path("api-auth/", include("rest_framework.urls"))]

pageturner/pageturner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('reviews.urls')),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
    path("api/", include("api.urls")),
    path("api/docs/schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pageturner/members/models.py
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from .utils import generate_avatar


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self", related_name="followed_by", symmetrical=False, blank=True
    )

    date_modified = models.DateTimeField(User, auto_now=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="images")
    profile_bio = models.CharField(null=True, blank=True, max_length=500)
    homepage_link = models.CharField(null=True, blank=True, max_length=100)
    instagram_link = models.CharField(null=True, blank=True, max_length=100)

    books_bookmarked = models.ManyToManyField(
        "reviews.Book", related_name="bookmarks", symmetrical=False, blank=True
    )
    books_read = models.ManyToManyField(
        "reviews.Book", related_name="read_books", symmetrical=False, blank=True
    )
    books_liked = models.ManyToManyField(
        "reviews.Book", related_name="liked_books", symmetrical=False, blank=True
    )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        avatar_svg = generate_avatar(instance.username)

        user_profile = Profile(user=instance)
        user_profile.profile_image.save(
            f"{instance.username}_avatar.svg", ContentFile(avatar_svg.encode("utf-8"))
        )
        user_profile.save()

        # Add the user to follow their own profile
        user_profile.follows.add(user_profile)
        user_profile.save()
    else:
        # If the user is not new, update the profile
        instance.profile.save()


class EmailSubscription(models.Model):
    email = models.EmailField(null=False, blank=False)

    def __str__(self):
        return f"{self.email}"


class Snippet(models.Model):
    user = models.ForeignKey(User, related_name="snippets", on_delete=models.CASCADE)
    body = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="snippet_like", blank=True)

    # keep count of likes

    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.user} " f"{self.created_at:%Y-%m-%d %H:%M}: " f"{self.body}"


class SharedSnippet(models.Model):
    original_snippet = models.ForeignKey(
        Snippet, on_delete=models.CASCADE, related_name="shared_snippet"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Shared by {self.user} at {self.shared_at}"


class Comment(models.Model):
    user = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    body = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    original_snippet = models.ForeignKey(
        Snippet, on_delete=models.CASCADE, related_name="replied_snippet"
    )
    likes = models.ManyToManyField(User, related_name="comment_like", blank=True)

    def __str__(self):
        return (
            f"Commented by {self.user} at {self.created_at} to {self.original_snippet}"
        )

    def number_of_likes(self):
        return self.likes.count()

pageturner/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <!-- Bootstrap link -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/259c88e539.js" crossorigin="anonymous"></script>

    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel="stylesheet">
    <link href="{% static 'main.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Gloock&family=Lora&display=swap" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>



    <title>{% block title %}PageTurner Reviews{% endblock %}</title>

<body>

<nav class="navbar navbar-expand-md">
    <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <a class="nav-link" href="{% url 'welcome_page' %}"><i class="fa-solid fa-book"></i> Home</a>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'profile' request.user.id %}">My Page</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile_list' %}">Community</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register_user' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <form action="{% url 'book_search' %}" class="form-inline my-2 my-md-0 mx-2" method="post">
                    {% csrf_token %}
                    <input aria-label="Search" class="form-control" name="searched" id="searched"
                           placeholder="Search by author, title or ISBN 🔍" type="text">
                </form>
            </li>
        </ul>
    </div>

</nav>

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button aria-label="Close" class="close" data-dismiss="alert" type="button">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}


    {% endif %}
</div>

{% block content %}
{% endblock %}
</body>