pageturner/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()

router.register(r"books", views.BookAPIViewSet)
router.register(r"book_collections", views.BookCollectionViewSet)

urlpatterns = [
    path("v1/", include("dj_rest_auth.urls")),
    path("v1/registration/", include("dj_rest_auth.registration.urls")),
    path("", include(router.urls)),
    path("recs/", views.RecommendedBooks.as_view(), name="recommended_books"),
    path(
        "personal_recs/",
        views.PersonalRecommendations.as_view(),
        name="personal_recommendations",
    ),
    path(
        "friends_recs/", views.FriendsRecommendations.as_view(), name="friends_recommendations"
    ),
    path("lucky_book/", views.show_lucky_book, name="lucky_book"),
    path("bookmark_book/<int:pk>/", views.bookmark_book, name="bookmark_book"),
    path("search_bar/", views.SearchBarApiListView.as_view(), name="search_bar"),
    path(
        "search_filters/",
        views.SearchFiltersApiListView.as_view(),
        name="search_filters",
    ),
    # # email subscription
    # path('email_subscription/', email_subscription, name="email_subscription")
]

urlpatterns += [path("api-auth/", include("rest_framework.urls"))]

pageturner/pageturner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', include('reviews.urls')),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
    path("api/", include("api.urls")),
    path("api/docs/schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pageturner/reviews/urls.py
from django.urls import path

# from api import views
# from rest_framework.routers import DefaultRouter
#
# router = DefaultRouter()
# router.register(r"books", views.BookAPIViewSet)

# urlpatterns = [
#     path('', views.welcome_page, name="welcome_page"),
#     path('book_search', views.book_search, name="book_search"),
#     # path('book_list', views.BookList.as_view(), name="book_list"),
#     path('book_detail/<int:pk>', views.BookDetail.as_view(), name="book_detail"),
#     path('book_detail/<int:pk>/review', views.ReviewCreateView.as_view(), name='create_review'),
#     path('review_like/<int:pk>', views.review_like, name="review_like"),
#     path('review_share/<int:pk>', views.review_share, name="review_share"),
#     path('review_comment/<int:pk>', views.review_comment, name="review_comment"),
#     path('genres/<str:genre>/', views.book_genres_list, name="book_genres_list"),
#     path('book_collections/<int:pk>/', views.show_book_collections, name='book_collections'),
#     path('show_lucky_book', views.show_lucky_book, name='show_lucky_book'),
#     path('book_like/<int:pk>', views.like_book, name='like_book'),

# ]

pageturner/reviews/models.py
from django.contrib.auth.models import User
from django.db import models


class Publisher(models.Model):
    """A company that publishes books"""

    name = models.CharField(max_length=50, help_text="The name of the Publisher.")

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    """A contributor to a Book, e.g. author, editor"""

    name = models.CharField(
        max_length=100, help_text="The name of the author", default=None
    )

    def __str__(self):
        return f"{self.name}"


class Book(models.Model):

    title = models.CharField(max_length=200, help_text="The title of the book.")
    rating = models.FloatField(
        default=0, help_text="The rating of the book", null=True, blank=True
    )
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    url = models.URLField(
        help_text="Link to the book page on Goodreads", default=None, null=True
    )
    cover_url = models.URLField(null=True, blank=True)
    summary = models.CharField(
        max_length=5000, help_text="Summary of the book", blank=True, null=True
    )
    main_genre = models.CharField(
        max_length=20, help_text="Main genre of the book", blank=True, null=True
    )
    secondary_genre = models.CharField(
        max_length=50, help_text="Secondary genre of the book", blank=True, null=True
    )
    genres = models.CharField(
        max_length=1000, help_text="Genres of the book (tags)", null=True, blank=True
    )
    number_of_pages = models.IntegerField(
        help_text="Number of pages in the book", blank=True, null=True
    )
    time = models.CharField(
        max_length=30, help_text="Time to finish the book", blank=True, null=True
    )
    amazon_link = models.URLField(help_text="Buy on Amazon", blank=True, null=True)
    audible_link = models.URLField(help_text="Buy on Audible", blank=True, null=True)
    year = models.IntegerField(
        help_text="Release year of the book", blank=True, null=True
    )
    format_book = models.CharField(
        max_length=50, help_text="Format of the book", blank=True, null=True
    )
    language = models.CharField(
        max_length=50, help_text="Language of the book", blank=True, null=True
    )
    isbn = models.CharField(max_length=15, help_text="ISBN", blank=True, null=True)
    isbn13 = models.CharField(max_length=15, help_text="ISBN13", blank=True, null=True)
    age = models.CharField(
        max_length=100, help_text="Age of book's audience", blank=True, null=True
    )
    main_age = models.CharField(
        max_length=20, help_text="Main age of the book", blank=True, null=True
    )
    country = models.CharField(
        max_length=50,
        help_text="Country associated with the book",
        blank=True,
        null=True,
    )
    part_of_series = models.CharField(
        max_length=200, help_text="Part of book series", blank=True, null=True
    )

    def __str__(self):
        return f"{self.title} / {self.author} / {self.main_genre} / {self.year}"

    def get_genres_list(self):
        return [genre.strip() for genre in self.genres.split(",")]

    def get_age_list(self):
        return [age_item.strip() for age_item in self.age.split(",")]

    def number_of_likes(self):
        return self.liked_books.count()


class BookCollection(models.Model):
    name = models.CharField(max_length=50, help_text="The name of the Book List")
    books = models.ManyToManyField(
        Book, related_name="book_lists", help_text="Books in the list"
    )
    list_cover = models.ImageField(upload_to="media/", null=True, blank=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    written_by = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    content = models.TextField(help_text="The Review text.")
    rating = models.CharField(
        help_text="The rating the reviewer has given.",
        max_length=10,
        null=True,
        blank=True,
    )
    date_created = models.DateTimeField(
        auto_now_add=True, help_text="The date and time the review was created."
    )
    date_edited = models.DateTimeField(
        null=True, help_text="The date and time this review was last edited."
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        help_text="The Book that this review is for.",
        related_name="reviews",
    )
    likes = models.ManyToManyField(
        User, related_name="review_like", blank=True, default=0
    )

    def __str__(self):
        return f"Review for {self.book} / {self.rating}"

    def number_of_likes(self):
        return self.likes.count()


class SharedReview(models.Model):
    original_review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="shared_review"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Shared by {self.user} at {self.shared_at}"


class ReviewComment(models.Model):
    user = models.ForeignKey(
        User, related_name="review_comment", on_delete=models.CASCADE
    )
    body = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="commented_review"
    )
    likes = models.ManyToManyField(User, related_name="review_comment_like", blank=True)

    def __str__(self):
        return f"Review commented by {self.user} at {self.created_at} to {self.review}"

    def number_of_likes(self):
        return self.likes.count()


class BookImport(models.Model):
    csv_file = models.FileField(upload_to="uploads/")
    date_added = models.DateTimeField(auto_now_add=True)


class AuthorImport(models.Model):
    csv_file = models.FileField(upload_to="uploads/")
    date_added = models.DateTimeField(auto_now_add=True)

pageturner/reviews/forms.py
from django import forms

from .models import Review, BookImport, ReviewComment, AuthorImport


class BookSearchForm(forms.Form):
    search = forms.CharField(
        min_length=3, max_length=50, required=False, label="Search"
    )


class BookImportForm(forms.ModelForm):
    class Meta:
        model = BookImport
        fields = ("csv_file",)


class AuthorImportForm(forms.ModelForm):
    class Meta:
        model = AuthorImport
        fields = ("csv_file",)


class ReviewForm(forms.ModelForm):
    content = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Type your review here.",
                "class": "form-control center-content",
            }
        ),
        label="",
    )
    rating = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Review
        exclude = ("date_created", "date_edited", "book", "written_by")


class ReviewCommentForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Type your comment here.",
                "class": "form-control",
            }
        ),
        label="",
    )

    class Meta:
        model = ReviewComment
        fields = ["body"]

pageturner/reviews/templates/reviews/base.html
{% extends "base.html" %}

{% load static %}

{% block title %}Welcome Page{% endblock %}

{% block content %}

<div class="container-xxl">
    <div class="text-center">
        <h1 class="mt-5">PageTurner Reviews</h1>
        <h3 class="mt-5">find your next best read and leave a review</h3>
        <p class="mt-2">Not sure where to start?</p>
    </div>

    <div class="button-container mt-3 mb-5">
        <a class="button-56" href="{% url 'book_list' %}">View Best Books of All Times</a>
    </div>

    <div class="random-books">
        {% if random_books %}
        {% for book in random_books %}
        <a href="{% url 'book_detail' book.id %}"><img src="{{ book.cover_url }}" class="random-book mt-2 mb-2"></a>
        {% endfor %}
        {% endif %}
        <div class="text-center">
            <div class="button-container mt-3 mb-5">
            <a href="{% url 'show_lucky_book' %}" type="button" class="button-56">💎 I'm feeling lucky 💎</a>
                </div>
        <h2 class="mt-5">Book Collections</h2>
            <div class="container">
    <div class="row mx-auto">
        {% for book_collection in book_collections %}
        <div class="card" style="width: 400px; border: transparent">
            <img src="{{ book_collection.list_cover.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <a href="{% url 'book_collections' book_collection.id %}"><h5 class="card-title">{{ book_collection.name }}</h5></a>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2 class="mt-5">Recommended for You</h2>
        {% for book in personal_recommendations %}
        <a href="{% url 'book_detail' book.id %}"><img src="{{ book.cover_url }}" class="random-book mt-2 mb-2"></a>
        {% endfor %}
                {% if friends %}
    <h2 class="mt-5">Because your friend @{{ random_friend.user.username }} liked</h2>
        {% for book in random_friends_recommendations %}
        <a href="{% url 'book_detail' book.id %}"><img src="{{ book.cover_url }}" class="random-book mt-2 mb-2"></a>
        {% endfor %}
                {% endif %}
</div>




            </div>
    </div>

    </div>


    <div class="container-xxl text-center">
        <div class="row">
            <div class="col-8">
                <div class="snippets-section">
                <h2 class="mt-5 mb-5">Recently shared snippets:</h2>

                {% for snippet in snippets %}
                <div class="comment-card mb-3">
                    <div class="container">
                        <div class="row">
                            <div class="col-2">
                                {% if snippet.user.profile.profile_image %}
                                <img class="profile-image-snippet" src="{{ snippet.user.profile.profile_image.url }}">
                                {% else %}
                                {{ profile.avatar_svg|safe }}
                                {% endif %}
                            </div>

                            <div class="col-10">
                                {{ snippet.body }} {% if request.user.id == snippet.user.id %} <a href="{% url 'snippet_delete' snippet.id %}"><i class="fa-solid fa-eraser"></i></a><a href="{% url 'snippet_edit' snippet.id %}"><i class="fa-solid fa-pencil"></i></a>{% endif %} <br/>
                                <small class="text-muted"> by <a href="{% url 'profile' snippet.user.profile.user.id %}">@{{ snippet.user.username }}</a>
                                     on
                                    {{ snippet.created_at }}
                                    {{ snippet.number_of_likes }}

                                    {% if user in snippet.likes.all %}
                                    <a href="{% url 'snippet_like' snippet.id %}"><i class="fa-solid fa-heart" style="color:red"></i></a>
                                    {% else %}
                                    <a href="{% url 'snippet_like' snippet.id %}"><i class="fa-regular fa-heart" style="color:red"></i></a>

                                    {% endif %}
                                    <a href="{% url 'snippet_share' snippet.id %}"><i class="fa-solid fa-share" style="color:gray"></i></a>

                                    <a href="{% url 'snippet_comment' snippet.id %}"><i class="fa-regular fa-comment"></i></a>
                                </small>

                            </div>

                        </div>
                    </div>
                </div>
                    {% if snippet.replied_snippet.all %}
{% for comment in snippet.replied_snippet.all %}
<div class="comment-card-reply mb-3">
    <div class="container">
        <div class="row">
            <div class="col-2">
                {% if comment.user.profile.profile_image %}
                <img class="profile-image-snippet" src="{{ comment.user.profile.profile_image.url }}">
                {% endif %}
            </div>

            <div class="col-10">
                {{ comment.body }} {% if request.user.id == comment.user.id %} <a href="{% url 'comment_delete' comment.id %}"><i class="fa-solid fa-eraser"></i></a> <a href="{% url 'comment_edit' snippet_id=snippet.id comment_id=comment.id %}"><i class="fa-solid fa-pencil"></i></a>{% endif %} <br/>
                <small class="text-muted"> replied by <a href="{% url 'profile' comment.user.profile.user.id %}">@{{ comment.user.username }}</a>
                    on {{ comment.created_at }}
                    {{ comment.number_of_likes }}

                    {% if user in comment.likes.all %}
                                    <a href="{% url 'comment_like' comment.id %}"><i class="fa-solid fa-heart" style="color:red"></i></a>
                                    {% else %}
                                    <a href="{% url 'comment_like' comment.id %}"><i class="fa-regular fa-heart" style="color:red"></i></a>

                                    {% endif %}
                </small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

                {% endfor %}
                </div>

            </div>

            <div class="col-4 mt-4">
                <div class="profile-section">
                    <h2 class="mt-5 mb-5">📖</h2>
                {% if form %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="button-56" type="submit">Share snippet!</button>

                </form>
                {% endif %}
            </div>
            </div>

        </div>


        {% endblock %}

pageturner/reviews/templates/reviews/book_collections.html
{% extends "base.html" %}

{% load static %}
{% load custom_filters %}

{% block title %}{% endblock %}

{% block content %}

<div class="container-xxl d-flex justify-content-center">
        <div class="text-center">

            <h1 class="mb-5">{{ book_collection.name }}</h1>
            {% for book in books %}
            <div class="book-container">
                <div class="container">
                    <div class="row">
                        <div class="col-3">
                            {% if book.cover_url %}
                    <img src="{{ book.cover_url }}" alt="Book Cover" class="book-cover-list align-self-center">
                    {% endif %}

                        </div>

                        <div class="col-9">
            <a class="book-info" href="{% url 'book_detail' book.pk %}"> <b>{{ book.title }}</b> by {{ book.author }}</a>
                            <p class="book-info mt-2">️<b>{{ book.rating }}⭐</b></p>
                            <p>
                                {% for genre in book.get_genres_list %}
                                <a href="{% url 'book_genres_list' genre %}" class="badge badge-pill" style="color: #ffffff; background-color: {{ genre|random_color }}; font-size: 16px;">{{ genre }}</a>
                                {% endfor %}

                                </p>
                            <div class="book-info-card">
                                <p class="py-5 px-5" align="justify"><em>{{ book.summary|truncatechars:300 }}</em></p>
                            <a href="{% url 'book_detail' book.id %}">View more details</a>
                                </div>
                <div class="buttons-user mt-5">
                        <a class="button-6" href="{% url 'mark_as_read' book.id %}">Mark as read</a>
                        <a class="button-6" href="{% url 'bookmark_book' book.id %}">Bookmark<i class="fa-solid fa-bookmark mx-2"></i></a>
                        <a class="button-6" href="{% url 'create_review' pk=book.id %}">Write a Review</a>
                        <a class="button-6" style="background-color:#FFEBD8" href="{{ book.amazon_link }}"><i class="fa-brands fa-amazon"></i></a>
                        <a class="button-6" style="background-color:#FFEBD8" href="{{ book.audible_link }}"><i class="fa-brands fa-audible"></i></a>
                        </div>
            </div>
                </div>
                    </div>
            </div>
            {% endfor %}


        </div>
    </div>

<div class="container-xxl d-flex justify-content-center">
        <div class="text-center">
            <div class="pagination">

            {% if books.has_previous %}
                <a class="mx-3" href="?page=1">First Page</a>
                <a href="?page={{ books.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
            {% endif %}

            <span class="current">
                Page {{ books.number }} of {{ books.paginator.num_pages }}
            </span>

            {% if books.has_next %}
                <a href="?page={{ books.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
                <a class="mx-3" href="?page={{ books.paginator.num_pages }}">Go to the Last Page</a>
            {% endif %}
        </div>
        </div>
</div>


{% endblock %}

pageturner/reviews/templates/reviews/book_detail.html
{% extends "base.html" %}

{% load custom_filters %}


{% load static %}

{% block title %}Book Details{% endblock %}

{% block content %}

<div class="container-xxl d-flex justify-content-center">
    <div class="text-center">

    <div class="container">
        <h2 class="mb-5">{{ book.title }}</h2>

            <div class="row">
                <div class="col-6">
                    <div>
                    {% if book.cover_url %}
                    <img src="{{ book.cover_url }}" alt="Book Cover" class="book-cover">
                    {% endif %}
                        </div>
                    <div class="buttons-user mt-5">
                        <a class="button-6" href="{% url 'mark_as_read' book.id %}">Mark as read</a>
                        <a class="button-6" href="{% url 'bookmark_book' book.id %}">Bookmark<i class="fa-solid fa-bookmark mx-2"></i></a>
                        <a class="button-6" href="{% url 'create_review' pk=book.id %}">Write a Review</a>
                    </div>
                    <div class="buttons-user mt-2">
                        <a class="button-6" style="background-color:#FFEBD8" href="{{ book.amazon_link }}"><i class="fa-brands fa-amazon"></i></a>
                        <a class="button-6" style="background-color:#FFEBD8" href="{{ book.audible_link }}"><i class="fa-brands fa-audible"></i></a>
                        {% if user.profile in book.liked_books.all %}
                            <a class="button-6" style="background-color:#FFEBD8" href="{% url 'like_book' book.id %}"><i class="fa-solid fa-heart" style="color:red"></i></a>
                            {% else %}
                            <a class="button-6" style="background-color:#FFEBD8" href="{% url 'like_book' book.id %}"><i class="fa-regular fa-heart" style="color:red"></i></a>
                        {% endif %}
                    </div>

                </div>

                <div class="col-6">
                    <div class="book-info-card">
                        <a class="book-info-detail" href="#"><b>{{ book.author }}</b></a>
                        <p class="rating-detail mt-3"> ⭐️{{ book.rating }}</p>
                        <p class="summary mt-3">{{ book.summary }}</p>
                        <p>

                        {% for genre in book.get_genres_list %}
                        <a href="{% url 'book_genres_list' genre %}" class="badge badge-pill" style="color: #ffffff; background-color: {{ genre|random_color }};">{{ genre }}</a>
                        {% endfor %}

                        </p>
                        <p>Number of pages: {{ book.number_of_pages }} <em>({{ book.time }} to read the book)</em></p>
                        <div class="button-container mt-3 text-center">
                            <a class="button-56" href="{{ book.url }}" target="_blank">View this book on Goodreads</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <h2>Reviews</h2>
        {% for review in reviews %}
        <div class="review-post">
                <div class="container">
                    <div class="row">
        <h4>Review by @{{ review.written_by.username }}</h4>
        <p>Rating: {{ review.rating }}
</p>
        <p>{{ review.content }}</p>
        <p>Created on: {{ review.date_created }}</p>
        {% if review.date_edited %}
            <p>Last edited on: {{ review.date_edited }}</p>
        {% endif %}
                    </div>
                    {{ review.number_of_likes }}

                    {% if user in review.likes.all %}
                        <a href="{% url 'review_like' review.id %}"><i class="fa-solid fa-heart" style="color:red"></i></a>
                    {% else %}
                        <a href="{% url 'review_like' review.id %}"><i class="fa-regular fa-heart" style="color:red"></i></a>
                    {% endif %}
                    <a href="{% url 'review_share' review.id %}"><i class="fa-solid fa-share" style="color:gray"></i></a>

                </div>
    </div>
        {% empty %}
            <p>No reviews available for this book.</p>
        {% endfor %}

    </div>
</div>



{% endblock %}

pageturner/reviews/templates/reviews/book_genres_list.html
{% extends "base.html" %}

{% load static %}
{% load custom_filters %}

{% block title %}Books with Genre: {{ genre }}{% endblock %}

{% block content %}

<div class="container-xxl d-flex justify-content-center">
        <div class="text-center">

            <h1 class="mb-5">Books with Genre: {{ genre }}</h1>
            {% for book in books %}
            <div class="book-container">
                <div class="container">
                    <div class="row">
                        <div class="col-2">
                            {% if book.cover_url %}
                    <img src="{{ book.cover_url }}" alt="Book Cover" class="book-cover-list">
                    {% endif %}

                        </div>

                        <div class="col-10">
            <a class="book-info" href="{% url 'book_detail' book.pk %}"> <b>{{ book.title }}</b> by {{ book.author }}</a>
                            <p class="book-info mt-2">⭐️<b>{{ book.rating }}</b></p>
                            <p>
                                {% for genre in book.get_genres_list %}
                                <a href="{% url 'book_genres_list' genre %}" class="badge badge-pill" style="color: #ffffff; background-color: {{ genre|random_color }};">{{ genre }}</a>
                                {% endfor %}

                                </p>
                            <p class="py-5 px-5" align="justify">{{ book.summary }}</p>
                <div class="buttons-user mt-5">
                        <a class="button-6" href="{% url 'mark_as_read' book.id %}">Mark as read</a>
                        <a class="button-6" href="{% url 'bookmark_book' book.id %}">Bookmark<i class="fa-solid fa-bookmark mx-2"></i></a>
                        <a class="button-6" href="{% url 'create_review' pk=book.id %}">Write a Review</a>
                        <a class="button-6" href="{{ book.amazon_link }}"><i class="fa-brands fa-amazon"></i></a>
                        <a class="button-6" href="{{ book.audible_link }}"><i class="fa-brands fa-audible"></i></a>
                        </div>
            </div>
                </div>
                    </div>
            </div>
            {% endfor %}


        </div>
    </div>

<div class="container-xxl d-flex justify-content-center">
        <div class="text-center">

<div class="pagination">
        {% if books.has_previous %}
                <a class="mx-3" href="?page=1">First Page</a>
                <a href="?page={{ books.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
        {% endif %}

        <span class="current">Page {{ books.number }} of {{ books.paginator.num_pages }}</span>

        {% if books.has_next %}
                <a href="?page={{ books.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
                <a class="mx-3" href="?page={{ books.paginator.num_pages }}">Go to the Last Page</a>
        {% endif %}
    </div>



{% endblock %}

pageturner/reviews/templates/reviews/create_review.html
{% extends "base.html" %}

{% load static %}

{% block title %}Review{% endblock %}

{% block content %}

<div class="container-lg d-flex justify-content-center">
    <div class="text-center">
        <h2>{{ book.title }}</h2>
        <div class="row">
            <div class="col-lg-6">
                <div class="book-detail-container">
                    <div class="book-cover">
                        {% if book.cover_url %}
                        <img src="{{ book.cover_url }}" alt="Book Cover" class="img-fluid">
                        {% endif %}
                    </div>
                </div>
            </div>
<div class="col-lg-6">
    <div class="container review-card">
        <div class="row">
            <form method="post">
                {% csrf_token %}
                <div class="rating container">
                    <div class="row">
                <div class="col-lg-4">
                    <h5>Your rating:</h5>
                </div>

                <div class="col-lg-8">
                    <div class="rating-card">
                    <div class="stars">
                        <i class="fas fa-star star"></i>
                        <i class="fas fa-star star"></i>
                        <i class="fas fa-star star"></i>
                        <i class="fas fa-star star"></i>
                        <i class="fas fa-star star"></i>
                    </div>
                    </div>
                    </div>
                </div>
                </div>

                            <div class="form-group">
                                <label for="{{ form.content.id_for_label }}"></label>
                                {{ form.content }}
                            </div>

                            <input type="hidden" id="id_rating" name="rating">

                        <div class="d-flex mt-4">

                            <button class="button-56" type="submit">Submit</button>
                        </div>

                    </form>
                    </div>

            </div>
        </div>
    </div>
</div>

<script src="{% static 'star-rating.js' %}"></script>
{% endblock %}

pageturner/reviews/templates/reviews/genres_list.html
{% extends "base.html" %}

{% load custom_filters %}

{% load static %}

{% block title %}Genres List{% endblock %}

{% block content %}


  {% for genre in unique_genres_list %}
<a href="#" class="badge badge-pill" style="color: #ffffff; background-color: {{ genre|random_color }};">{{ genre }}</a>
  {% empty %}
  <li>No genres available</li>
{% endfor %}

{% endblock %}